test_database_name = "test3"
database_name = "evil_car"
roads = "roads"
violations_collection = "violations"
testingCollection = "testingCollection"
starting_longitude = "startingLongitude"
starting_latitude = "startingLatitude"
obstacles_collection = "obstacles" 
